#!/bin/bash
### BEGIN INIT INFO
# Provides:          servoblaster
# Required-Start:    hostname $local_fs
# Required-Stop:
# Should-Start:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop servod.
# Description:       This script starts/stops servod.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
#. /lib/init/vars.sh

#OPTS="--idle-timeout=20000"
OPTS=""

res=0

start(){
echo -en "Starting:\t\t"
/usr/local/sbin/servod $OPTS >/dev/null
if [ $? = 0 ]; then
	echo '[  OK  ]'
else
	echo '[ FAIL ]'
fi
}
stop(){
echo -en "Stopping:\t\t"
killall servod 2>&1
if [ `ps -ef | grep "servod" | grep -v grep | grep -c .` = 0 ]; then
	echo '[  OK  ]'
else
	echo '[ FAIL ]'
	return 1
fi
}

case "$1" in
  start) start;;
  restart|reload|force-reload)
	stop 
	if [ ! -e /dev/servoblaster ]; then
		start
	else
		echo "ERROR: Stop not successful"
	fi
	;;
  stop)	stop;;
  status)
	if [ `ps -ef | grep servod | grep -v grep | grep -c .` = 0 ]; then
		echo "Not Running"
		res=1
	else
		echo "Running"
	fi
	;;
  *)
	echo "Usage: servoblaster [start|stop|status]" >&2
	res=3
	;;
esac

exit $res

